repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: ea782651a7e32f40a3d13b76c79d5a2474ee8723
    hooks:
      - id: prettier
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: b762b86f28cb684ac10287ecb0e4420d5c320ab3
    hooks:
      - id: shellcheck
